openapi: 3.0.0
info:
  version: 1.0.0
  title: OAuth2 Refresh Token Management
  description: OAuth2 refresh token management microservices endpoints.
  contact:
    email: stevehu@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /oauth2/refresh_token:
    get:
      description: Return all refresh tokens
      operationId: getAllRefreshToken
      parameters:
        - name: page
          in: query
          description: Page number
          required: true
          schema:
            type: integer
            format: int32
        - name: pageSize
          in: query
          description: Pag size
          required: false
          schema:
            type: integer
            format: int32
        - name: userId
          in: query
          description: Partial userId for filter
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RefreshToken'
      security:
        - refresh_token_auth:
            - oauth.refresh_token.r
  '/oauth2/refresh_token/{refreshToken}':
    delete:
      description: Delete a refresh token
      operationId: deleteRefreshToken
      parameters:
        - name: refreshToken
          in: path
          description: Refresh Token
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid refresh token supplied
        '404':
          description: Refresh token not found
      security:
        - refresh_token_auth:
            - oauth.refresh_token.w
    get:
      description: Get a refresh token
      operationId: getRefreshToken
      parameters:
        - name: refreshToken
          in: path
          description: Refresh token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshToken'
        '400':
          description: Invalid refresh token supplied
        '404':
          description: Refresh token not found
      security:
        - refresh_token_auth:
            - oauth.refresh_token.r
            - oauth.refresh_token.w
servers:
  - url: 'https://oauth2.networknt.com'
components:
  securitySchemes:
    refresh_token_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://localhost:8888/oauth2/code'
          scopes:
            oauth.refresh_token.w: write oauth refresh token
            oauth.refresh_token.r: read oauth refresh token
  schemas:
    RefreshToken:
      type: object
      required:
        - refreshToken
        - userId
        - clientId
      properties:
        refreshToken:
          type: string
          description: refresh token
        userId:
          type: string
          description: user id
        clientId:
          type: string
          description: client id
        scope:
          type: string
          description: service scopes separated by space