

# Handler middleware chain configuration
---
enabled: true

#------------------------------------------------------------------------------
# Support individual handler chains for each separate endpoint. It allows framework
# handlers like health check, server info to bypass majority of the middleware handlers
# and allows mixing multiple frameworks like OpenAPI and GraphQL in the same instance.
#
# handlers  --  list of handlers to be used across chains in this microservice
#               including the routing handlers for ALL endpoints
#           --  format: fully qualified handler class name@optional:given name
# chains    --  allows forming of [1..N] chains, which could be wholly or
#               used to form handler chains for each endpoint
#               ex.: default chain below, reused partially across multiple endpoints
# paths     --  list all the paths to be used for routing within the microservice
#           ----  path: the URI for the endpoint (ex.: path: '/v1/pets')
#           ----  method: the operation in use (ex.: 'post')
#           ----  exec: handlers to be executed -- this element forms the list and
#                       the order of execution for the handlers
#
# IMPORTANT NOTES:
# - to avoid executing a handler, it has to be removed/commented out in the chain
#   or change the enabled:boolean to false for a middleware handler configuration.
# - all handlers, routing handler included, are to be listed in the execution chain
# - for consistency, give a name to each handler; it is easier to refer to a name
#   vs a fully qualified class name and is more elegant
# - you can list in chains the fully qualified handler class names, and avoid using the
#   handlers element altogether
#------------------------------------------------------------------------------
handlers:
  # Light-framework cross-cutting concerns implemented in the microservice
  - com.networknt.exception.ExceptionHandler@exception
  - com.networknt.metrics.MetricsHandler@metrics
  - com.networknt.traceability.TraceabilityHandler@traceability
  - com.networknt.correlation.CorrelationHandler@correlation
  - com.networknt.openapi.OpenApiHandler@specification
  - com.networknt.openapi.JwtVerifyHandler@security
  - com.networknt.body.BodyHandler@body
  - com.networknt.audit.AuditHandler@audit
  - com.networknt.sanitizer.SanitizerHandler@sanitizer
  - com.networknt.openapi.ValidatorHandler@validator
  - com.networknt.cors.CorsHttpHandler@cors
  # Customer business domain specific cross-cutting concerns handlers
  # - com.example.validator.CustomizedValidator@custvalidator
  # Framework endpoint handlers
  - com.networknt.health.HealthGetHandler@health
  - com.networknt.info.ServerInfoGetHandler@info
  # - com.networknt.metrics.prometheus.PrometheusGetHandler@getprometheus
  # Business Handlers
  - com.networknt.oauth.user.handler.Oauth2UserGetHandler
  - com.networknt.oauth.user.handler.Oauth2UserPostHandler
  - com.networknt.oauth.user.handler.Oauth2UserPutHandler
  - com.networknt.oauth.user.handler.Oauth2UserUserIdDeleteHandler
  - com.networknt.oauth.user.handler.Oauth2UserUserIdGetHandler
  - com.networknt.oauth.user.handler.Oauth2PasswordUserIdPostHandler


chains:
  default:
    - exception
    - metrics
    - traceability
    - correlation
    - specification
    - security
    - body
    - audit
    - sanitizer
    - validator
    - cors

paths:
  - path: '/oauth2/user'
    method: 'options'
    exec:
      - cors
  - path: '/oauth2/user'
    method: 'get'
    exec:
      - default
      - com.networknt.oauth.user.handler.Oauth2UserGetHandler
  - path: '/oauth2/user'
    method: 'post'
    exec:
      - default
      - com.networknt.oauth.user.handler.Oauth2UserPostHandler
  - path: '/oauth2/user'
    method: 'put'
    exec:
      - default
      - com.networknt.oauth.user.handler.Oauth2UserPutHandler
  - path: '/oauth2/user/{userId}'
    method: 'options'
    exec:
      - cors
  - path: '/oauth2/user/{userId}'
    method: 'delete'
    exec:
      - default
      - com.networknt.oauth.user.handler.Oauth2UserUserIdDeleteHandler
  - path: '/oauth2/user/{userId}'
    method: 'get'
    exec:
      - default
      - com.networknt.oauth.user.handler.Oauth2UserUserIdGetHandler
  - path: '/oauth2/password/{userId}'
    method: 'post'
    exec:
      - default
      - com.networknt.oauth.user.handler.Oauth2PasswordUserIdPostHandler
  - path: '/oauth2/password/{userId}'
    method: 'options'
    exec:
      - cors
      
  - path: '/health/com.networknt.oauth2-user-1.0.0'
    method: 'get'
    exec:
      - health

  - path: '/server/info'
    method: 'get'
    exec:
      - info

